apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps-auto
  namespace: argocd
spec:
  goTemplate: true

  generators:
    - git:
        repoURL: https://github.com/abeguin/argocd.git
        revision: main
        directories:
          - path: apps/*/*
          - path: apps/*/templates
            exclude: true

  template:
    metadata: # e.g. paperless-abe for apps/paperless/abe
      name: '{{ index (splitList "/" .path.path) 1 }}-{{ index (splitList "/" .path.path) 2}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/abeguin/argocd.git
        targetRevision: main
        # chart in apps/<app>
        path: '{{ index (splitList "/" .path.path) 0 }}/{{ index (splitList "/" .path.path) 1 }}'
        helm:
          releaseName: '{{ .path.path | replace "/" "-" }}'
          valueFiles:
            - '{{ index (splitList "/" .path.path) 2 }}/values.yaml'

      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ index (splitList "/" .path.path) 1 }}-{{ index (splitList "/" .path.path) 2}}'

      syncPolicy:
        automated:
          enabled: true # Enables automated syncing of the application ( true by default ).
          prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
          selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
          allowEmpty: false # Allows deleting all application resources during automatic sy
        syncOptions:
          - CreateNamespace=true