paperless:
  enabled: true
  containerPort: 8000
  replicaCount: 1
  repository: ghrc.io/paperless-ngx/paperless-ngx
  tag: latest
  consumeSync:
    enabled: true
  configMap:
    name: paperless-env
  service:
    port: 8000
    name: paperless-web

postgresql:
  enabled: true
  auth:
    secretName: paperless-db-secret
    secretKeys:
      userPasswordKey: password
      postgresPasswordKey: postgres-password
      usernameKey: username
      databaseKey: database
    username: paperless
    database: paperless
  primary:
    persistence:
      enabled: true
      size: 1Gi
  networkPolicy:
    enabled: false

redis:
  enabled: true
  fullnameOverride: redis
  auth:
    enabled: false

gotenberg:
  enabled: true
  image: gotenberg/gotenberg
  tag: 8.22
  containerPort: 3000
  servicePort: 3000

tika:
  enabled: true
  image: apache/tika:latest
  containerPort: 9998
  servicePort: 9998

cron:
  backup:
    enabled: true
    schedule: "0 13 * * *"
  restoreTest:
    enabled: true
    schedule: "30 13 * * *"


ingress:
  enabled: true

