paperless:
  enabled: true
  containerPort: 8000
  replicaCount: 1
  repository: ghrc.io/paperless-ngx/paperless-ngx
  tag: latest
  consumeSync:
    enabled: true
  configMap:
    name: paperless-env
  service:
    port: 8000
    name: paperless-web

postgresql:
  enabled: true
  auth:
    secretName: paperless-db-secret
    secretKeys:
      userPasswordKey: password
      postgresPasswordKey: postgres-password
      usernameKey: username
      databaseKey: database
    username: paperless
    database: paperless
  primary:
    persistence:
      enabled: true
      size: 1Gi
  networkPolicy:
    enabled: false
  image:
    tag: sha256-2b08aaced99e1aff63ec8fff5a07bd0eb2e70cde4769df218d16fa4a542bbd45

redis:
  enabled: true
  fullnameOverride: redis
  auth:
    enabled: false
  image:
    tag: sha256-b9905a48b6726c0d59df323c83db4c6253a00851ab3604d0edcc32e925e3659f

gotenberg:
  enabled: true
  image: gotenberg/gotenberg:8.22
  tag: 8.22
  containerPort: 3000
  servicePort: 3000

tika:
  enabled: true
  image: apache/tika:latest
  containerPort: 9998
  servicePort: 9998

cron:
  backup:
    enabled: true
    schedule: "0 13 * * *"
  restoreTest:
    enabled: true
    schedule: "30 13 * * *"


ingress:
  enabled: true

