ingress:
  host: abe.paperless

endpoints:
  publicURL: "http://abe.paperless"
  tika: "http://tika.paperless-abe.svc.cluster.local:9998"
  gotenberg: "http://gotenberg.paperless-abe.svc.cluster.local:3000"
  dbHost: "db-postgresql.paperless-abe.svc.cluster.local"
  redisURL: "redis://redis-master.paperless-abe.svc.cluster.local:6379"

volumes:
  data: /Users/afo/paperless/abe/data
  media: /Users/afo/paperless/abe/media
  export: /Users/afo/paperless/abe/export
  consume: /Users/afo/paperless/abe/consume
