apiVersion: v1
kind: ConfigMap
metadata:
  name: paperless-env
  labels:
    {{- include "paperless.labels" . | nindent 4 }}
data:
  {{- /* Base env from values.env */}}
  {{- range $k, $v := .Values.env }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
  PAPERLESS_PUBLIC_URL: {{ .Values.endpoints.publicURL | quote }}
  PAPERLESS_TIKA_ENDPOINT: {{ .Values.endpoints.tika | quote }}
  PAPERLESS_TIKA_GOTENBERG_ENDPOINT: {{ .Values.endpoints.gotenberg | quote }}
  PAPERLESS_DBHOST: {{ .Values.endpoints.dbHost | quote }}
  PAPERLESS_REDIS: {{ .Values.endpoints.redisURL | quote }}
