apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps-auto
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/abeguin/argocd.git
        revision: main
        directories:
          - path: apps/*/*

  template:
    metadata:
      name: "{{index (splitList \"/\" path) 1}}-{{index (splitList \"/\" path) 2}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/abeguin/argocd.git
        targetRevision: main
        path: "{{index (splitList \"/\" path) 0}}/{{index (splitList \"/\" path) 1}}"
        helm:
          releaseName: "{{index (splitList \"/\" path) 1}}-{{index (splitList \"/\" path) 2}}"
          valueFiles:
            - "{{index (splitList \"/\" path) 2}}/values.yaml"

      destination:
        server: https://kubernetes.default.svc
        namespace: "{{index (splitList \"/\" path) 1}}-{{index (splitList \"/\" path) 2}}"

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true