apiVersion: argoproj.io/v1beta1
kind: ApplicationSet
metadata:
  name: apps-smart
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/abeguin/argocd.git
        revision: main
        directories:
          - path: apps/*/*

  template:
    metadata:
      name: "{{{path.basename}}-{{index (splitList \"/\" path) 1}}-{{index (splitList \"/\" path) 2}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/abeguin/argocd.git
        targetRevision: main
        path: "{{path}}"

        helm:
          releaseName: "{{path.basename}}-{{index (splitList \"/\" path) 1}}-{{index (splitList \"/\" path) 2}}"
          valueFiles:
            - values.yaml

      destination:
        server: https://kubernetes.default.svc
        namespace: "{{path.basename}}-{{index (splitList \"/\" path) 1}}-{{index (splitList \"/\" path) 2}}"

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      syncOptions:
        - CreateNamespace=true
